
# 设置网站的基本信息
app_setting:
     title: "RSSinn - RSS小黑屋"
     description: "Powered by FastAPI"
     swagger_ui_parameters: {defaultModelsExpandDepth: -1, filter: True}

# Upptime (https://upptime.js.org) is the open-source uptime monitor and status page, powered entirely by GitHub Actions, https://github.com/upptime/upptime
upptime:
     enabled: True
     jsdelivr_CDN: True
     github: "chinobing"
     repo: "upptime-rssinn"

# Set proxy for crawling webpage, fetch_proxy_settings will be overwritten if individual proxy is set.
fetch_proxy_settings:
    simple:
      proxy_server: ""  # Supports http and socks proxies.
      proxy_username: ""
      proxy_password: ""
    proxy_pool:
      server: "http://127.0.0.1:5010" #http://127.0.0.1:5010 , https://github.com/jhao104/proxy_pool

# Settings for cache
related_settings:
    cached:
        enabled: True
        method: "redis" # in-memory or redis
        redis_url: "redis://:password@ip_address:port" # eg. redis://:password@ip_address:port
        expiration_time: 30 # Time in seconds for cached feeds to expire after