
#设置网站的基本信息
app_setting:
     title: "RSSinn - RSS小黑屋"
     description: "Powered by FastAPI"
     swagger_ui_parameters: {defaultModelsExpandDepth: -1, filter: True}

#Upptime (https://upptime.js.org) is the open-source uptime monitor and status page, powered entirely by GitHub Actions, https://github.com/upptime/upptime
upptime:
     enabled: True
     jsdelivr_CDN: True
     github: "chinobing"
     repo: "upptime-rssinn"

# Playwright Browser Connection
fetch_proxy_settings:
    PROXY_SERVER: ""  # Supports http and socks proxies.
    PROXY_USERNAME: ""
    PROXY_PASSWORD: ""
