name: RSSinn Deploy CD
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: settings for redis
        run: |
          sed -i 's~redis_url~${{ secrets.REDIS_URL }}~g' settings.yaml
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIVE_SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_USER_PASSWORD }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            git pull ${{secrets.REPO_URL}}
            fuser -n tcp -k 28085
            fuser -n tcp -k 28085
            export PATH=/root/.local/bin:$PATH
            nohup pdm run uvicorn run:app --host 0.0.0.0 --port 28085 > log.txt 2>&1 &